### ISSUE TITLE
generated rust code breaks when object literal name is `Option`

### ISSUE THREAD

**Issue by darklyspaced** [glideapps/quicktype#2385]
there is a name conflict between `Option<T>` and the `Option` generated by quicktype, resulting in rust complaining that `Option` doesn't have any generic arguments as it's definition has been overridden from the prelude.

### MRE
```json
{
    "option": {
        "name": "test",
        "age": 5
    }
}
```
```rust
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct Welcome {
    pub option: Option<Option>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Option {
    pub name: Option<String>,
    pub age: Option<i64>,
}
```
the rust code produces by quicktype fails to compile.

this should be pretty simple to fix: just add a case when a struct is called `Option`. call it something else and just `#[serde(rename = "option")]`.

**Comment by dvdsgl** [comment]
Adding `Option` to the keywords list will fix this.

**Comment by schani** [comment]
**Triage sweep finding** (systematic backlog triage, assisted by Claude) — confirmed reproducible on current master (v23.3.0, `68ecb284`), despite this issue being closed.

**Root cause:** a JSON property named `"option"` still makes quicktype emit `pub struct Option`, which shadows the prelude's `Option<T>` and breaks compilation as soon as the same file also has an actual `Option<T>` (e.g. from any optional field).

The earlier fix added lowercase `"option"` to the `keywords` array in `packages/quicktype-core/src/language/Rust/constants.ts` (line 75, `// Conflict between std::Option and potentially generated Option`), consumed via `forbiddenNamesForGlobalNamespace` in `RustRenderer.ts`. That renames snake_case *field* names (confirmed: a field named `option` becomes `welcome_option` in the repro below), but the PascalCase *type* namer still produces `Option` for a struct derived from that property name — the case-sensitive forbidden-name check never catches it because the keyword list only has the lowercase form.

**Assessment:** severity medium (non-compiling output whenever a struct is named "Option" *and* the file also uses `Option<T>` for any optional field — a fairly narrow but concrete trigger). Fix difficulty easy: add `"Option"` (PascalCase) to the keywords array — arguably also `String`/`Vec`/`Box`/`HashMap` for the same class of shadowing bug.

**Reproduction:**
```
node dist/index.js --lang rust --src-lang json multi.json
```
```json
[
  {"option": {"name": "test", "age": 5}},
  {"option": {"name": "x"}}
]
```
Produces:
```rust
pub struct MultiElement {
    #[serde(rename = "option")]
    multi_option: Option,     // <-- unqualified `Option` type reference
}

pub struct Option {           // <-- struct shadows the prelude's Option<T>
    name: String,
    age: Option<i64>,         // <-- fails to compile: `Option<i64>` now resolves to the local struct, which takes no generics
}
```
