### ISSUE TITLE
[BUG]: Generates an extra class if using $refs to URLs that don't exist

### ISSUE THREAD

**Issue by andrewducker** [glideapps/quicktype#2633]
We don't have all of our schemas sitting on a website, we just use them as unique IDs.  And generating references to them causes an extra, unnecessary file to be generated.

For extra weirdness, changing the $id to be a non-URL string makes it work correctly.

## Issue Type
output

## Context (Environment, Version, Language)

Input Format: Schema
Output Language: Verified with C#, Java, and Rust

CLI, 23.0.170

## Description

I've attached 3 schema files - Person, Product and Location.
Both of Person and Product have a property called "Where" which is a Location type (in the third file).

We don't have our schemas stored on a webserver, so the schema IDs aren't real URLs.

What we've discovered is that if the $IDs are "fake" URLs (like `https://company.com/quicktypes.location.json`) then the generate step also introduces a "WhereClass", identical to the Location class.  And it uses that WhereClass rather than the Location class.

If I then change the ID for the Location to "AAAA", and reference that from the two other classes, then it only generates three classes, and uses the Location class as you'd expect.

But then if you change *all three of the files* to use simple strings as their IDs then it goes back to creating a WhereClass again.

## Input Data

[QuickTypes.zip](https://github.com/user-attachments/files/16281383/QuickTypes.zip)

Please see the attached zip.  I've created a folder for:
1) All three files use "fake" URLs.
2) The "location" file uses an ID of AAAA, and that's how the others reference it.
3) All three files use IDs that are simple strings ("AAAA","BBBB",and "CCCC")

They were then generated into Rust files using the command:
`quicktype --lang rust --src-lang schema --out generated.rs --src .\product.json --src .\person.json --src .\location.json`

## Expected Behaviour / Output

Case 2 is correct.

## Current Behaviour / Output

Case 1 and 3 look wrong to me.  I don't understand why they're creating the extra unnecessary class.

## Steps to Reproduce

See above.

**Comment by andrewducker** [comment]
I finally got to the bottom of this - I hadn't realised that mirroring the folder structure in the namespaces would mean that things worked, and I managed to do that in a way that Quicktype would be happy with.

**Comment by schani** [comment]
**Triage note** (systematic backlog sweep, assisted by Claude): this issue is closed but the underlying bug is still confirmed reproducible on current master (v23.3.0, `68ecb284`) with the schemas originally attached here (the "1ExtraClass" case). The commenter's workaround (renaming `$id` away from a URL) avoids it, but the URL-`$id` case still generates a spurious duplicate class.

**Root cause**: in `packages/quicktype-core/src/input/JSONSchemaInput.ts`, `Canonizer.addSchema` (~line 540) registers a schema root as `Ref.root(address)`, i.e. a ref with an *empty* path:
```ts
new Location(Ref.root(address), Ref.root(undefined)),
```
But when a `$ref` is later resolved against the `$id` map via `resolveVirtualRef` (~line 749), the resulting top-level ref carries a path with a single `[Root]` element instead of `[]`. `Ref.equals` treats `[]` and `[Root]` as different refs even though both stringify to the same thing (`file#`), so the `typeForCanonicalRef` cache (~line 803) misses on the second lookup, and `toType` builds the class a second time — producing e.g. `WhereClass` as a duplicate of `Location`. The "2Working" case in the original attachment happens to sidestep this via the alt-base fallback path in `resolveVirtualRef`, which is why some `$id` layouts appeared to work and others didn't.

**Assessment**
- Severity: medium — output still compiles and is usable, but produces redundant duplicate types whenever a schema references another top-level schema by URL `$id`.
- Difficulty: moderate — likely a small normalization fix (treating `[]` and `[Root]` root paths as equal in `Ref`/`Canonizer`), but the resolver code is order-sensitive and delicate, so this needs care and regression testing across the various `$id`/`$ref` resolution paths.

**Reproduction** (using the issue's own "1ExtraClass" schemas):
```
node dist/index.js --lang rust --src-lang schema --src product.json --src person.json --src location.json
```
`product.json`:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://company.com/quicktypes.product.json",
  "title": "Product",
  "type": "object",
  "properties": {
    "productId": { "type": "integer" },
    "where": { "$ref": "https://company.com/quicktypes.location.json" }
  }
}
```
`person.json`:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://company.com/quicktypes.person.json",
  "title": "Person",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "where": { "$ref": "https://company.com/quicktypes.location.json" }
  }
}
```
`location.json`:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://company.com/quicktypes.location.json",
  "title": "Location",
  "type": "object",
  "properties": {
    "Latitude": { "type": "integer" },
    "Longitude": { "type": "integer" }
  }
}
```
Result: `Person`/`Product` reference a generated `WhereClass` struct that's a byte-for-byte duplicate of `Location`, and `Location` itself is emitted separately, unused.

**Comment by andrewducker** [comment]
Impressive work by Claude. Nice root cause analysis! 

(Also, great that you've gone through these old bugs and triaged them)

**Comment by schani** [comment]
> Impressive work by Claude. Nice root cause analysis!
> 
> (Also, great that you've gone through these old bugs and triaged them)

Fable is a beast!

**Comment by andrewducker** [comment]
Yeah, I was a sceptic until around Christmas, but it's been impossible to not appreciate it since then.
